### PR TITLE
Add Best Practices to a prominent place

### PR DESCRIPTION
**Pull request by mareklibra**
Fixes: FLPATH-1805

Screenshot from 2024-10-31 14-02-14

### CODE REVIEW

**Review by pkliczewski — COMMENTED** [review]
/lgtm

**Comment by batzionb** [comment]
this needs to be available only in 1.3 documentation, which isn't created yet
@masayag how should this be handled?

**Comment by masayag** [comment]
> this needs to be available only in 1.3 documentation, which isn't created yet @masayag how should this be handled?

For now, it should go under https://github.com/parodos-dev/parodos-dev.github.io/tree/main/content/main/docs/serverless-workflows

After the releasing 1.3, we'll copy https://github.com/parodos-dev/parodos-dev.github.io/tree/main to https://github.com/parodos-dev/parodos-dev.github.io/tree/main/content/1.3.x

**Comment by mareklibra** [comment]
> For now, it should go under https://github.com/parodos-dev/parodos-dev.github.io/tree/main/content/main/docs/serverless-workflows

So recent state of this PR is ok.

> After the releasing 1.3, we'll copy https://github.com/parodos-dev/parodos-dev.github.io/tree/main to https://github.com/parodos-dev/parodos-dev.github.io/tree/main/content/1.3.x

We will need to change the references throughout multiple documents here as well since they point to the `main` branch of the `https://github.com/parodos-dev/serverless-workflows`. We will probably need to branch-out serverless-workflows for that.

**Review by masayag — APPROVED** [review]

**Comment by masayag** [comment]
I meant using https://github.com/parodos-dev/serverless-workflows/tree/v1.3.x but TBH, it makes more sense to create the release-1.3 folder and then change it instead of having to do the other way around (changing the main to point to 1.3 and after creating release-1.3, to change the main branch to point on other main branches).
I'll take care of updating the links once we create the release-1.3 folders.

**Pull request merged**
